### ISSUE TITLE
Doesnt seem to build on android

### ISSUE THREAD

**Issue by sitefinitysteve** [pocketsmith/nativescript-raygun#2]
iOS seems to work just fine, any ideas?

```
Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.gson.internal.bind.TimeTypeAdapter$1 conflict: /Users/steve/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.3.1/ecb6e1f8e4b0e84c4b886c2f14a1500caf309757/gson-2.3.1.jar and /Users/steve/Dropbox/Projects/Apps/OutbreakHelp/OutbreakHelp/node_modules/nativescript-raygun/platforms/android/libs/gson-2.1.jar
    at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
    at com.telerik.metadata.Builder.build(Builder.java:38)
    at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by sitefinitysteve** [comment]
Edit: Closing, was android related, however opening another issue

**Comment by maknz** [comment]
Hmm, it looks like you already have gson (2.3.1) from a different library. I'm not entirely sure how we get around that, but if you delete gson from node_modules/nativescript-raygun/platforms/android/libs, it should work as a temporary workaround.

**Comment by sitefinitysteve** [comment]
It was added from this issue https://github.com/NativeScript/nativescript-cli/issues/1549

I yanked that back out, and it builds again, but still tanks at runtime, do you not get this?
https://goo.gl/photos/LN4uE4wpKV8W9ZvU6

**Comment by maknz** [comment]
Looks like the plugin isn't being copied over. Can I suggest blowing your Android platform away and re running? That sometimes fixes these things.

I haven't yet tried the plugin in a {N} 1.6 app, but we'll look at that soon.

**Comment by sitefinitysteve** [comment]
Yeah I've platform removed\added till the cows come home... so she does work just fine for you then eh

(Yeah this is 1.6)

**Comment by maknz** [comment]
Always worked fine in 1.5 for us. I wouldn't rule out something in 1.6 breaking things.

I'll probably do some work on this stuff at the weekend. I'll try reproduce and hunt the issue down. We'll be upgrading our own app to 1.6 so it'll need to work for us.

**Comment by sitefinitysteve** [comment]
Thanks, hey, I assume this doesn't log any JS error right?  ...any idea if their JS provider relies on browser?

**Comment by maknz** [comment]
Fatal JS errors get turned into native crashes I believe, so I think they'll get caught by the platform-specific handler.

**Comment by maknz** [comment]
@sitefinitysteve quick heads up that this plugin seems to be working fine with our app on 1.6.
