### ISSUE TITLE
dSYM For ios crash 

### ISSUE THREAD

**Issue by AntonioCuevaUrraco** [pocketsmith/nativescript-raygun#3]
Hello, First thank you for the work :-)

I did the set up of the plugin as described and all working fine. I had the duplicate gson-2.3.1.jar error but it solved by manually deleting it.

In android the crash have all the useful information, but on iOS the crash are not really useful as I can only see 

```
    0   MyApp                          0x00000001000bac08 0x100014000 + 683016
    1   MyApp                          0x00000001000d9cf4 0x100014000 + 810228
    2   MyApp                          0x00000001005ab108 0x100014000 + 5861640
    3   MyApp                          0x00000001005ac1b4 0x100014000 + 5865908
    4   UIKit                             0x000000018878cc28 0x188740000 + 314408
```

Do you know how to grab the dSYM that will make it print JS Errors? @jasssonpet

**Comment by maknz** [comment]
You need to upload your dSYMs for your builds to Raygun. We use Raygun Sidekick which automatically finds your builds and you can one-click upload them. https://raygun.com/blog/2014/04/upload-dsyms-straight-from-your-mac-using-the-raygun-sidekick/

Then re-process/symbolicate your crash reports and they'll start showing reasonable stuff.

**Comment by AntonioCuevaUrraco** [comment]
Thanks, I was having problems to install the Sidekick (it was saying is broken all the time).
But after uploading the dSYMs I don't see the JS error that are the real causes of problems. Are you able to see those? The last time I checked the issue I got that apple doesn't let you write on their crash reports hence the NS trace is not there and only on console, but I was hopping raygun was getting that too and sending it... I need to find a way to create proper crash reports for iOS attaching the NS trace

**Comment by maknz** [comment]
It's up to NativeScript to put any native crash information into the exception that crashes the app. This is simply a NativeScript plugin to install Raygun which monitors for native crashes.

FWIW, I do see JS errors in our Android crash reports, we don't see many iOS crash reports though, so it could well be that they don't track the JS error well.

**Comment by AntonioCuevaUrraco** [comment]
Thank you @maknz and you are right is up to NS what is there on the crash report but they can do nothing about adding additional information for iOS so we get no JS errors. 

If the crash happens on JS level we get a crash report but missing the start of the trace so we can not see the root of the problem.

I am asking about some insights in this thread if you are interested https://github.com/NativeScript/ios-runtime/issues/554#issuecomment-222185638

For Raygun this JS error trace could be added as extra data to the report. But that's another issue :-)
